### ISSUE TITLE
CNI Library (VPP and OVS) Repo Location

### ISSUE THREAD

**Issue by Billy99** [Billy99/user-space-net-plugin#2]
At first pass, added the CNI VPP Library in a separate repo (https://github.com/Billy99/cnivpp). Should CNI VPP and CNI OVS be in separate repos or subfolders of this repo?

FYI - This may eventually be folded back into https://github.com/intel/vhost-user-net-plugin/, but same question remains.

**Comment by rkamudhan** [comment]
+1 to move the cnivpp in userspace net plugin repo.

**Comment by Billy99** [comment]
OK, when the vhost user space CNI project is renamed to the UserSpace CNI (https://trello.com/c/7ziDrztB/4-change-name-of-vhostuser-cni-to-userspace-cni), I'll port the current Billy99/user-space-net-plugin code over and collapse the repos into one.

**Comment by Billy99** [comment]
Went ahead and tackled this because cross repo vendor files were causing issues. Billy99/cnivpp is now merged into UserSpace and Billy99/cnivpp will no longer be maintained.
