### ISSUE TITLE
CNI should return CNI type package types.PrintResult()

### ISSUE THREAD

**Issue by rkamudhan** [Billy99/user-space-net-plugin#4]
CNI userspace should return types.PrintResult() instead of nil.

**Comment by Levovar** [comment]
it should return current.Result IMHO
types.Result is the older, v0.2.0 format, but I think we should aim for CNI version 0.3.1 at least

**Comment by rkamudhan** [comment]
yeap.. updating the PR..

**Comment by rkamudhan** [comment]
Take care of arg,Netns issue as well :)

**Comment by Billy99** [comment]
OK, I assume you mean add logic to process the input, something like:
   netns, err := ns.GetNS(args.Netns)
Is there an issue or trello on it?

**Comment by rkamudhan** [comment]
No, not currently.. we can create one for it..

**Comment by Billy99** [comment]
Also being tracked via Trello:
https://trello.com/c/rFJJDJkk/5-update-the-cni-result
