### ISSUE TITLE
Use a package manager to build the project

### ISSUE THREAD

**Issue by Levovar** [Billy99/user-space-net-plugin#5]
Instead of storing the vendor dependencies inside the source of the repo, we could state in the project description that we use Glide
Then, we only need to include a glide.yaml into the source containing the exact version / commit hash etc. of our dependencies

In the Makefile we can add a glide install before the building of the component

**Comment by Billy99** [comment]
glide.yaml and glide.lock added. There was discussion online on whether to check-in the vendor files or not and no real winner of the discussion. They were already checked in, so I stayed with that model. The Makefile is not currently managing glide, I'll work on that next. For now, use: glide update --strip-vendor

**Comment by Billy99** [comment]
Tracked by Trello:
https://trello.com/c/OoQNksnz/12-use-a-package-manager-to-build-the-project
